### ISSUE TITLE
issue is it 1.12?

### ISSUE THREAD

**Issue by willywanka** [faizaand/Prison#226]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### What's the problem?
receive this error when I type /prison in chat
[13:23:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'prison' in plugin Prison v2.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at me.sirfaizdat.prison.core.Configuration.reload(Configuration.java:61) ~[?:?]
	at me.sirfaizdat.prison.core.Configuration.getConfig(Configuration.java:71) ~[?:?]
	at me.sirfaizdat.prison.core.MessageUtil.get(MessageUtil.java:34) ~[?:?]
	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:59) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	... 15 more
[13:24:34] [Server thread/INFO]: [0;31;22mPrison [0;37;22m> [m[0;31;1mPlease specify a subcommand.[m
[13:24:34] [Server thread/INFO]: [0;37;22m============== [0;36;22mPrison [0;37;22m==============
[0;30;1m<> = Required argument    [] = Optional argument
[0;36;22m/prison reload [0;36;22m [0;30;1m-[0;37;22m Reload Prison's configuration and all components.
[0;36;22m/prison update [0;36;22m [0;30;1m-[0;37;22m Downloads the latest version of Prison.
[0;36;22m/prison version [0;36;22m [0;30;1m-[0;37;22m View information about Prison.
[m
[13:24:40] [Server thread/INFO]: [0;31;22mPrison [0;37;22m> [m[0;37;22mYou are running the [0;36;22mlatest version[0;37;22m.[m
[13:24:46] [Server thread/WARN]: Unexpected exception while parsing console command "prison reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'prison' in plugin Prison v2.4.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:637) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at me.sirfaizdat.prison.core.Configuration.reload(Configuration.java:61) ~[?:?]
	at me.sirfaizdat.prison.core.MessageUtil.reload(MessageUtil.java:50) ~[?:?]
	at me.sirfaizdat.prison.core.Prison.reload(Prison.java:252) ~[?:?]
	at me.sirfaizdat.prison.core.cmds.CmdReload.execute(CmdReload.java:36) ~[?:?]
	at me.sirfaizdat.prison.core.Command.run(Command.java:88) ~[?:?]
	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:73) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	... 8 more

### What's happening?
not working properly and ranks wont function 

Added these plugins(25): WorldEdit, InventoryFull, NoFallDamage, TokenShop, WorldGuard, PermissionsEx, CS-CoreLib, Vault, PrisonPicks, Essentials, PlotSquared, Multiverse-Core, Citizens, Quests, Multiverse-Inventories, EssentialsChat, CommandNPC, MineResetLite, EZPrestige, EssentialsSpawn, QuickSell, AreaShop, Prison, PrisonUtils, QuickMarket

### How do we recreate the problem?

haven't changed much only permissions on permissionsEx

**Comment by DylanFPS** [comment]
Judging by the error info, nope.
